version: '3'

services:
  elastic-search-engine:
    image: elasticsearchengine
    build:
      context: .
      dockerfile: Dockerfile
    networks:
        - reverseproxy
        - default
    labels:
        - "traefik.enable=true"
        - "traefik.backend=elastic"
        - "traefik.frontend.rule=Host:elastic.wtakumi.io"
        - "traefik.docker.network=traefik_reverseproxy"
    ports:
    - "3000:3000"

networks:
    reverseproxy:
        external:
            name: traefik_reverseproxy