version: '3'

services:
  elastic-search-engine:
    image: codebadger/elasticsearchengine
    build: .
    networks:
        - reverseproxy
        - default
    labels:
        - "traefik.enable=true"
        - "traefik.backend=elastic"
        - "traefik.frontend.rule=Host:elastic.wtakumi.io"
        - "traefik.docker.network=traefik_reverseproxy"
    ports:
    - "3001:3001"

networks:
    reverseproxy:
        external:
            name: traefik_reverseproxy